### ISSUE TITLE
iRuby looks/acts like iPython

### ISSUE THREAD

**Issue by seanodell** [jupyter/nbviewer#398]
I just installed iRuby, and after firing it up with "iruby notebook" every notebook I create and run gives me Python-specific errors. It's as if, even though I started iruby, it started up as a plain old ipython notebook.

Any ideas why?

**Comment by Carreau** [comment]
Do you by any chance have IPython 3-dev installed? If so IRuby might not yet be compatible with recent IPython.

Envoyé de mon iPhone

**Comment by seanodell** [comment]
ipython version is 2.3.1. I just did a pip install yesterday; it's probably a newer version, but I don't think I have ipython-dev installed.

**Comment by Carreau** [comment]
Hum. Should work. 
I'm not familiar with IRuby.

I would try asking on minad/IRuby repository. IIRC IRuby command does some specific stuff to set up some IPython variable. Feel free to ping us on the issue there, but the creator might know what the issue is immediately while I might take us a few hours to install IRuby understand code before figuring out why. 
So you will probably get a quicker answer. 



Envoyé de mon iPhone

**Comment by seanodell** [comment]
What the dickens? That's where I thought I was posting ... too many windows, too little brain.

**Comment by Carreau** [comment]
No harm done, we are also on many repos, and I actually did'nt saw in first response that this was nbviewer repo :-) 

Have fun with IRuby

Envoyé de mon iPhone

**Comment by bollwyvl** [comment]
Apparently mis-filed... please repoen if it is nbviewer related!
