### ISSUE TITLE
Error 503 backend read error

### ISSUE THREAD

**Issue by kubu4** [jupyter/nbviewer#408]
backend read error
Guru Mediation:

Details: cache-lax1427-LAX 1423803157 4031173432

Varnish cache server

---
Getting this message when trying to view my notebooks.  All notebooks are in a Github repo.

http://nbviewer.ipython.org/github/kubu4/fish546_2015/blob/master/RNAseq_TopHat_Cufflinks_Workflow.ipynb

http://nbviewer.ipython.org/github/kubu4/fish546_2015/blob/master/Week01_CoreFile_ID.ipynb

**Comment by rgbkrk** [comment]
Weird. I can get at that directly using an IP for one of the nodes. Fastly is reporting the strangest error (they operate the varnish cache for CDN). Digging.

**Comment by rgbkrk** [comment]
Ah, your notebook is 87540.354 KB. Sadly, our error message isn't getting propagated up to Fastly. GitHub's API only lets us display notebooks < 25 MB.

**Comment by kubu4** [comment]
Whoa!  Thanks for looking into this and thanks for the info.  Good to know.

**Comment by gumption** [comment]
I was getting this same error a short time ago when I tried to access a notebook I recently updated:

http://nbviewer.ipython.org/github/gumption/Python_for_Data_Science/blob/master/Python_for_Data_Science_all.ipynb

I re-ran nbconvert on the notebook locally to verify there were no rendering problems with the HTML. I pushed the new HTML file to the GitHub repository and then tried the link on nbviewer again ... and it worked.

This could be a coincidence, but I thought I'd mention it in case it is of use.

**Comment by rgbkrk** [comment]
Weird. When I go at it directly against one of our servers it's working just fine. http://104.130.161.116/github/gumption/Python_for_Data_Science/blob/master/Python_for_Data_Science_all.ipynb

Not so on Fastly though. @ejgreenberg, any ideas?

**Comment by rgbkrk** [comment]
Side note: Wow, what a gorgeous notebook @gumption!

**Comment by gumption** [comment]
Thanks for the positive feedback on the notebook - it was a lot of fun assembling it.

I can view the notebook fine now. I updated it yesterday on GitHub, but had forgotten to verify it was still viewable at nbviewer.python.org.  When I checked today, I get the same error message reported by @kubu4 (which I discovered through [googling github error 503 backend read error](https://www.google.com/q=github%20error%20503%20backend%20read%20error . After regenerating and committing a new HTML version, I checked back, and everything was fine again.

Actually, I checked back again via Safari first - and it rendered fine there - and then when I refreshed the page in Chrome (my default browser), it rendered fine there again too.

In any case, everything is fine now, I just wanted to note the steps I took, in case they actually had some effect (rather than the resolution of the problem and the steps I took simply being a coincidence, which I still believe is the most likely explanation), for the potential benefit of anyone else who encounters the error.

**Comment by gumption** [comment]
Also, forgot to note that (1) my notebook is about 200K, so the 25MB size limitation was not a factor ... and (2) I have been experiencing periodic issues in Chrome (probably due to my tendency to have about 100 tabs across several windows open at any given time) ... which is why I tried Safari, which I only use in "private" mode for testing.

**Comment by gumption** [comment]
Brief update: I have gotten this error several more times recently (I've made a few additional updates to my notebook), but only in Chrome. Whenever I visit the notebook in Safari, all is well ... and if I refresh the page enough times in Chrome, I can eventually view it.

**Comment by ejgreenberg** [comment]
I'd file a ticket with Fastly support, if you haven't already. They're your
best bet and very speedy! Also, check community.fastly.com

**Comment by kubu4** [comment]
After reducing the size of my notebook below the 25MB limit, I'm still periodically getting this error (using Firefox). If the notebook doesn't load initially (and gives me the 503 error), refreshing the page a few times will usually pull it up.

Oh, and @gumption, (@rgbkrk beat me to it), but that notebook is definitely pretty boss!

**Comment by gumption** [comment]
@kubu4 Thanks for the positive feedback. 

@ejgreenberg I'm not sure how to act on your suggestion. When I go to the Fastly website, and search for nbviewer, it doesn't return any results. Is there a specific link you can point to through which I can file a ticket?

**Comment by kubu4** [comment]
@gumption, I interpreted @ejgreenberg's response to be intended for @rgbkrk, since he had asked her about Fastly.

**Comment by gumption** [comment]
Ah - thanks for the clarification.

**Comment by dbogdanov** [comment]
I have the same issue with a 3.9Mb notebook file
http://nbviewer.ipython.org/github/MTG/essentia/blob/master/src/examples/tutorial/essentia_tutorial_standard.ipynb

**Comment by minrk** [comment]
Thanks. It went down this morning, but is back up now.
