### ISSUE TITLE
Cannot download the dataset

### ISSUE THREAD

**Issue by rakesh11rc** [jupyter/nbviewer#444]
Hello,

I tried to download the dataset and it throwed 400:Bad Request error. Below is the screen shot of the error. May I know the problem for such an error and possible soultion.

![image](https://cloud.githubusercontent.com/assets/12033211/7229831/6329a8da-e768-11e4-8221-03d4e970efd0.png)

Regards,
Rakesh

**Comment by bollwyvl** [comment]
We'll need to know which notebook URL you used!

**Comment by rakesh11rc** [comment]
Here is the url :
http://nbviewer.ipython.org/urls/s3-eu-west-1.amazonaws.com/recsysrules2015/RecSysRules2015-Dataset.ipynb

**Comment by bollwyvl** [comment]
So it looks like however S3 is set up such that we (the nbviewer server)
can't access it. Perhaps many people viewed lots of S3 items in the last
bit of time, or for some other reason we have been blocked. Since you can
download the file directly, you can repost it somewhere else. I've done
that here with a gist:
http://nbviewer.ipython.org/gist/anonymous/b0cb4aea7ac6fb5d622d

If this is a recurrent issue, we may have to do an API-level integration,
such as with GitHub!

**Comment by bollwyvl** [comment]
For future reference, here's the [boto SDK](https://boto.readthedocs.org/en/latest/ref/s3.html?highlight=s3#module-boto.s3) for doing AWS stuff.

The URL structure would be like this:
```
http://nbviewer.ipython.org/s3/s3-eu-west-1/recsysrules2015/RecSysRules2015-Dataset.ipynb
```
There is no real concept of nested directories, so it could also be a list provider for a bucket:
```
http://nbviewer.ipython.org/s3/s3-eu-west-1/recsysrules2015/
```

Seems pretty straightforward!

**Comment by rakesh11rc** [comment]
Thank you very much for the information!

**Comment by rgbkrk** [comment]
This was also related to #446, sorry about that. All set now!
