### ISSUE TITLE
SVG images no longer work in nbviewer

### ISSUE THREAD

**Issue by mwiebe** [jupyter/nbviewer#458]
The notebook

http://nbviewer.ipython.org/github/libdynd/libdynd/blob/master/docs/intro-01/HowDyNDViewsMemory.ipynb

includes lots of inline svg images, and used to work fine. Now just the text of the links are displaying in place of the images.

**Comment by bollwyvl** [comment]
Thanks  for the report. I think it's not the svg, per se: all the svg
`![]()` are wrapped in `<center>`  tags.  Take those away, and it works
locally, will try a gist. That's the nickle fix.

The same condition is exhibited by nbconvert directly... But this is
upstream there, likely this is a mistune issue! We'll see about fixing it
for real, but... Long term,. I can imagine the embedded html eventually
getting stripped. However, since the notebook ui supports it now,
nbviewer/nbconvert should, too!

**Comment by mwiebe** [comment]
Good to know, thanks for looking into it!

**Comment by bollwyvl** [comment]
See lepture/mistune#51 and jupyter/nbconvert#45.

Basically a Decision needs to be made as to whether we are going to be spec-driven, or legacy driven.

So I am going to close this issue. If you want to center stuff, you'd can abuse a span-level element with style:

http://nbviewer.ipython.org/gist/anonymous/25ce8fcad2354bfe322f
