### ISSUE TITLE
nbviewer should allow to log as a GitHub user to display private notebooks

### ISSUE THREAD

**Issue by scls19fr** [jupyter/nbviewer#475]
Hello,

nbviewer should allow to log as a GitHub user

For example this document
http://nbviewer.ipython.org/github.com/scls19fr/initiation_python_traitement_donnees/blob/master/tp/tp_meteo_temperature/tp_meteo_temperature.ipynb
is in a private GitHub repository.

It will be nice if, logged as a GitHub (I could, but also every people who have at least read access) could see it using nbviewer.

Kind regards

**Comment by scls19fr** [comment]
Sorry it work outside of nbviewer

**Comment by rgbkrk** [comment]
We'll (probably) *never* support logins on nbviewer itself because of arbitrary javascript execution on rendered notebooks. We don't want to be the source of leaked GitHub OAuth credentials via user content.

Glad you're happy with the GitHub rendering - it's probably going to be the most solid bet for private notebooks other than converting via `nbconvert` yourself.

**Comment by scls19fr** [comment]
Thanks
