### ISSUE TITLE
Jupyter>>nbviewer slides Fail, notebook view fine

### ISSUE THREAD

**Issue by angisgrate** [jupyter/nbviewer#484]
When using the web based iPython Notebook/Jupyter capability, i created a notebook with markdown cells of text and code cells to display the code and plots for matplotlib and bokeh. I then download that as .ipynb open with sublime, copy and paste to git, then access it on nbviewer through my git account. When looking at it here: 
http://nbviewer.ipython.org/github/angisgrate/test/blob/master/pyohio3.ipynb
in notebook view, it works fine. the markdown, code, and plot steps are all there. 
When switching to slides view, the intent of the creation needed for the presentation, this code blocks occurs first, blocking out the first 10 markdown steps and all the matplotlib steps, rendering this weird code without the plots:
http://nbviewer.ipython.org/format/slides/github/angisgrate/test/blob/master/pyohio3.ipynb 

How can i fix this asap?? I've looked through and there was a similar problem in 2014 with slides, but it yielded an actual "Error" that i'm not seeing, just this contorted view

**Comment by damianavila** [comment]
This is something weird, in the conversion part of the bokehjs seems to be lost...
This deserve more investigation, are you getting similar problems when you convert it using nbconvert?
Also which version of Bokeh are you using?

**Comment by angisgrate** [comment]
@damianavila yes it is very weird...no i have not yet tried nbconvert itself because i figured it would only yield the same problem. i want to present it with nbviewer, and since i'm using everyon from the web-based system, i haven't went to terminal to use nbconvert.  i am using the most up-to-date bokeh, 0.9.2

**Comment by bollwyvl** [comment]
It's breaking on the naive <body> regex I put in there for stripping out
the vanilla nbviewer slides stuff...

https://github.com/jupyter/nbviewer/blob/8aee4d40b5c14e3735eb20a3943ec1f66d0d604b/nbviewer/formats.py#L34

... which may not even be necessary, especially once nbconvert upgrades to
reveal 3+.

The near term fix is a ? after the first *. so that it only matches the
FIRST instance of <body>. Even if I got that out tonight, it might be a
tick before it deploys.

In the nearer term (like right now), try generating your notebook with the
Bokeh CDN assets, as then it won't inject the script with the offending
<body>:
https://gist.github.com/tonyfast/fae0eacea79bbd28996d

This will have the additional advantage of making your file much smaller.

>

**Comment by angisgrate** [comment]
@bollwyvl great, i'll definitely try that! Does that also explain why it is not displaying my screenshots properly? I took them out of the second try i did because they were not showing up, just as blank icons. 

For the screenshots, i was using: <img src="PC Model list ss.png"> with markdown and from IPython.display import Image
Image(filename='PC iPS.png') 

for code, just to see if either worked, and neither one did. This presentation is Saturday, so nothing like waiting and then encountering errors!

**Comment by bollwyvl** [comment]
I don't see the screenshots in the github repo, hence markdown can't find
them.

Image() should embed them.... do you have an example of them not working?

**Comment by angisgrate** [comment]
http://nbviewer.ipython.org/github/angisgrate/test/blob/master/pyohio2.ipynb its this one @bollwyvl both do not work

**Comment by angisgrate** [comment]
@damianavila @bollwyvl okay, so using the bokeh CDN model, it resolved the coding error and prevention of using slides, but it just eliminated the bokeh plots all together. it's the same as if i were to delete them from my iPython Notebook, except that they are still present in the iPython Notebook view of nbviewer. This is so puzzling. It is in my github code here, copied from the ipynb export from my web based ipython notebook: https://github.com/angisgrate/test/blob/master/test10.ipynb
and then when i view it here: http://nbviewer.ipython.org/github/angisgrate/test/blob/master/test10.ipynb it all still shows up (except the 2 screen shots--viewed as icons)
and then slides view doesn't show the bokeh plots at all [nor the screenshots] but matplotlib plot is shown: http://nbviewer.ipython.org/format/slides/github/angisgrate/test/blob/master/test10.ipynb

quite puzzling, guys

**Comment by bollwyvl** [comment]
First off, thanks again for finding the problem with bokeh embedded vs slides: we'll get a fix out for that, as that just shouldn't happen, but the priority is a bit diminished as the CDN approach is far more robust.

Screenshot issues:
The images are not in the repo. Markdown doesn't embed anything: since your stuff looks fine locally, presumably, the Notebook can resolve that URL, next to your notebook. when nbviewer looks on github, it can't go back and reach into your computer. Crack open the console (F12) and you'll see that the screenshots are 404ing. You have to add and commit them to the repo, or put them someplace else... imgur.com is lovely for that kind of thing.

Everything else:
In your markdown, you are not closing your `<font>` tags. This works in the `html` format because the notebook format is very linear, stable and forgiving. reveal does Crazy Things With The DOM to make slides, flying them all over the place, hiding them, resizing/zooming them. It just can't keep up with the structure of the document you are describing. To get an idea of what Reveal sees, try pressing escape in a slideshow and navigating around. Your bokeh slides are there, but it has no idea how to get to them.

Here, I have stripped all of your font tags out, and everything looks "fine"†:

http://nbviewer.ipython.org/format/slides/gist/anonymous/3b450cc43f8150187572

One take away: don't use `<font>` tags. The modern equivalents would be:
- CSS. this works out pretty well in the notebook and with markdown:
```html
%%html
<style>
h1{color: dodgerblue;}
h2{color: midnightblue;}
/* etc */
</style>
```
  - you can put that wherever: in a slideshow, you can't `skip` it, as don't think it will get drawn, but you can put it as a subslide at the end of your presentation
- if you feel like you must customize things on a per-item level in your markdown, use:
```html
<span style="color: midgnightblue;">whatever</span>
```
  - it is a known issue that nbviewer can't do markdown inside nested html, another thing that the Notebook allows, even though it's explicitly forbidden in the Markdown spec. So don't do it, for now.

## †: bokeh css in slides
bokeh apparently uses tables for layout, and hides its tables' cells' borders with `!important` CSS directives that targets things in `#notebook`. Well, it also just messes with `table` straight up. Anyhow, the `slides` format doesn't have a `#notebook` element, so bokeh's CSS doesn't quite work, and you get these mondrian-lookin' things. @damianavila and I will have to do some looking into that to figure out where the correct fix should occur, whether on nbviewer, nbconvert, bokeh...or something. In the near term, you could hack it yourself with some more custom css, but I don't have a ready snippet to help you... the interplay of lots and lots of selectors, the many copies of bokeh you load, `!important` and reveal (which is generally a pain to style around) and bootstrap is... non-trivial. I think it's solveable with a bit of namespacing upsptream somewhere, but it's going to be hard to suss out with just the browser and luck.

**Comment by damianavila** [comment]
>It is in my github code here, copied from the ipynb export from my web based ipython notebook: https://github.com/angisgrate/test/blob/master/test10.ipynb
and then when i view it here: http://nbviewer.ipython.org/github/angisgrate/test/blob/master/test10.ipynb it all still shows up (except the 2 screen shots--viewed as icons)
and then slides view doesn't show the bokeh plots at all [nor the screenshots] but matplotlib plot is shown: http://nbviewer.ipython.org/format/slides/github/angisgrate/test/blob/master/test10.ipynb

For the screenshot try using Image as @bollwyvl suggested (IIRC you can also try putting the images in the repo too, but not sure about that, I have not tested for a while).
For the missing bokeh plot, IIRC, you are using subslides of fragments to show them, please change them to slides an try again (I am suspecting you hit a bug we have already fixed in nbconvert master but still not deployed in nbviewer).

**Comment by damianavila** [comment]
>Anyhow, the slides format doesn't have a #notebook element, so bokeh's CSS doesn't quite work, and you get these mondrian-lookin' things. @damianavila and I will have to do some looking into that to figure out where the correct fix should occur, whether on nbviewer, nbconvert, bokeh...or something.

Probably something I missed of it was lost in some of the rewritten... we should probably add it in the slide template somehow...

**Comment by angisgrate** [comment]
@bollwyvl i'm glad i could help reveal a problem. I'm working on the screenshots now. The link you sent here: "http://nbviewer.ipython.org/format/slides/gist/anonymous/3b450cc43f8150187572" is indeed "fine" because its the same as if i had deleted the screen shots and the bokeh plots, so the font tag change was super helpful at least. i didn't realize that you and @damianavila hadn't resolved the bokeh CSS issue when i tried using it. I guess in the very least i have a working slidesshow, so thank you, and i'll be working today to try and implement the changes you suggested. Thank you!!

**Comment by angisgrate** [comment]
Unfortunately, the Bokeh CDN approach failed after a successful first attempt. In the notebook it errors: 

from bokeh.io import output_notebook
from bokeh.resources import CDN
output_notebook(resources=CDN)


BokehJS successfully loaded.

Warning: BokehJS previously loaded
Javascript error adding output!
ReferenceError: Bokeh is not defined
See your browser Javascript console for more details.

Nothing works with it.

**Comment by damianavila** [comment]
Mmm... try this:

1. Clean output of all the cell
2. Restart the kernel
3. Reload the page

and execute the cells again... also if you see any errors, please open the jsconsole and paste the output...

**Comment by bollwyvl** [comment]
> Warning: BokehJS previously loaded

Yeah, you should probably call that exactly once per browser/notebook session. The gist above is still working on nbviewer!

**Comment by angisgrate** [comment]
@damianavila i checked the console and it wasn't anything major so i just did the 1/2/3 you suggested before you even suggested them! as @bollwyvl  said it usually happens a lot, but since i was restarting it more frequently i thought it would work. oh well. but here is the finished project gentlemen: http://nbviewer.ipython.org/format/slides/github/angisgrate/test/blob/master/analyze.ipynb#/
thank you so much for your help!! SO much! i used the <span> style, the bokeh CDN, and switched out the one bokeh plot and made them all individual slides. Thank you so much guys, i hope the error gets resolved soon though. Cheers!

**Comment by bollwyvl** [comment]
Great, glad we could help.

You have a few dangling </span>s:
http://nbviewer.ipython.org/format/slides/github/angisgrate/test/blob/master/analyze.ipynb#/14

**Comment by bollwyvl** [comment]
No update here in a while... the original issue (bad regex) has been fixed, so I'm going to close this!
