### ISSUE TITLE
Github Notebook redering does not respect Bootstrap columns

### ISSUE THREAD

**Issue by LukasDrude** [jupyter/nbviewer#514]
According to this [blog post](http://blog.jupyter.org/2015/05/07/rendering-notebooks-on-github/) this is the right place to point out Notebook rendering issues.

Suppose we are using the Boostrap [grid options](http://getbootstrap.com/css/#grid-example-basic), meaning that I add HTML output to my notebook which makes use of the classes `row` and `col-md-1` and so on, the corresponing rendering does not display all columns correctly.

Screenshot, how it should render:
![target](https://cloud.githubusercontent.com/assets/1886882/10471997/4ff7e98c-71e9-11e5-8298-9b3c9f18a887.png)

Screenshot, how it is currently rendering:
<img width="873" alt="screen shot 2015-10-13 at 20 32 02" src="https://cloud.githubusercontent.com/assets/1886882/10472016/8a36e2b0-71e9-11e5-991d-3780e5d8d1f3.png">

Since the Jupyter notebooks are build with Bootstrap, Bootstrap should also be supported by the Github rendering of Jupyter notebooks.

Can I somehow improve my bug report?

**Comment by bollwyvl** [comment]
An immutable link to a broken notebook is always helpful... But this seems
pretty easy to reproduce!

Your search stuff looks pretty cool... Though widgets will definitely not
be supported on Github or nbviewer proper any time soon.

**Comment by LukasDrude** [comment]
Thank you for your reply, the URL to the notebook repository is this: https://github.com/LukasDrude/jupyter_search
This is a basic search feature for now, because I am really missing something similar for notebooks.

By now, I do not expect the Widget to work but I think, the static HTML content with Bootstrap classes should work.

**Comment by parente** [comment]
The index.ipynb in that repository appears to render correctly on nbviewer as of today: http://nbviewer.jupyter.org/github/LukasDrude/jupyter_search/blob/master/index.ipynb. GitHub maintains its own implementation of notebook rendering so I don't think there's much we can do to change its handling of Bootstrap. These days, it's not safe to assume Bootstrap is present for layout anyway (e.g., JupyterLab doesn't use it), but I wouldn't expect anyone to know that back in 2015 when this issue was originally opened.

I'm going to close this out as resolved, at least on nbviewer as it stands.

**Comment by LukasDrude** [comment]
Yes, thank you.
