### ISSUE TITLE
issues rendering image.

### ISSUE THREAD

**Issue by Carreau** [jupyter/nbviewer#526]
In one of our most famous notebook:

http://nbviewer.ipython.org/url/norvig.com/ipython/xkcd1313-part2.ipynb

![screen shot 2015-10-28 at 09 55 41](https://cloud.githubusercontent.com/assets/335567/10796143/11d5bb3a-7d5a-11e5-9156-665ebd4901d8.png)

**Comment by bollwyvl** [comment]
The issue is the inline html persnicketiness of mistune.

The offending input is:
```json
"<a href="http://xkcd.com/1313">![](http://imgs.xkcd.com/comics/regex_golf.png)</a> ",
```

Had he used the `[![](http://imgs.xkcd.com/comics/regex_golf.png)](http://xkcd.com/1313)` notation, it would work fine, i'm guessing.

However, this is bothersome as, according to the ["spec"](https://daringfireball.net/projects/markdown/syntax#html):
 
> Unlike block-level HTML tags, Markdown syntax is processed within span-level tags.

So, likely to make things work, we'd want to use the following [options](https://github.com/lepture/mistune#options) in nbconvert:

```python
def markdown2html_mistune(source):
    """Convert a markdown string to HTML using mistune"""
    return MarkdownWithMath(renderer=IPythonRenderer(
        escape=False,
        parse_inline_html=True, # should be default, isn't?
        parse_block_html=True,  # why not!
    )).render(source)
```

...or somehow overload it in nbviewer.

XSS be damned!

**Comment by fperez** [comment]
I believe this can be closed, correct?
