### ISSUE TITLE
Python Bootcamp gives 400 error

### ISSUE THREAD

**Issue by daedie** [jupyter/nbviewer#562]
Notebook for the Python bootcamp returns a 400 error when trying to access it. It was working perfectly yesterday, began this morning. I cleared my cache out. I'm using Chrome on Ubuntu.

**Comment by bollwyvl** [comment]
Hi! Can you provide the URL that is not working?

If it is hosted on github, sometimes we have sporadic, non-deterministic availability issues.

A useful work-around during such periods is to copy the "raw" URL of the notebook into [rawgit](http://rawgit.com), and use that URL on the homepage of nbviewer to view your notebook.

**Comment by minrk** [comment]
We hit the GitHub rate limit again today. I'm digging into the (2GB) logs to see if I can figure out a way to reduce the number of API requests we make, or if maybe our caching isn't working properly.

If our caching is working properly, we may want to just turn up a few knobs - default minimum time up to one hour from ten minutes, etc.

We might also consider caching intermediate upstream API requests more aggressively, so that we don't need to fetch listings, etc. as often. Right now, caching is all or nothing, there's no caching between nbviewer and GitHub.

**Comment by daedie** [comment]
It is back up now, thanks. Hopefully those knobs keep getting turned!
