### ISSUE TITLE
nbviewer not rendering style

### ISSUE THREAD

**Issue by albahnsen** [jupyter/nbviewer#569]
When I render locally using `ipython nbconvert slides_edcs_fraud_detection.ipynb --to slides --post serve`
I got the following
![image](https://cloud.githubusercontent.com/assets/3617224/12897048/3e7bb922-ce73-11e5-9b92-4b5477472f2a.png)
That stlyle is done by having the following on the last cell
![image](https://cloud.githubusercontent.com/assets/3617224/12897093/7e6c800c-ce73-11e5-92cf-d028e90e5e73.png)

But then when push to github and open on nbconvert I lost all the style 
![image](https://cloud.githubusercontent.com/assets/3617224/12897031/2a704268-ce73-11e5-94ad-8566399d349d.png)

**Comment by rdipietro** [comment]
+1

For example the following are night and day:

Bad: https://github.com/barbagroup/AeroPython/blob/master/lessons/07_Lesson07_methodOfImages.ipynb
Good: http://nbviewer.jupyter.org/github/barbagroup/AeroPython/blob/master/lessons/07_Lesson07_methodOfImages.ipynb

**Comment by bollwyvl** [comment]
@albahnsen that's pretty odd... i thought our general approach was to not strip much of anything... i'll see if i can create a smaller test case...

@rdipietro I think we're talking about two different things here... github will probably never support any custom formatting.

**Comment by rdipietro** [comment]
Can you elaborate? I think it's the same issue: the HTML that's embedded in
the notebook for custom styling is getting stripped out.

**Comment by rdipietro** [comment]
Oh, nevermind, I see. His wasn't even getting rendered outside of GitHub.

**Comment by parente** [comment]
Today, I see the same behavior on https://nbviewer.jupyter.org/format/slides/gist/parente/2bff9eed810ef9557b32db3581c20228#/ as I do when rendering the same notebook as slides using `jupyter nbconvert jupyter-nbviewer-569.ipynb --to slides --post serve`. That is, the custom `h1` style only takes effect if the cell containing the `display` call is *not* a skipped slide. Skipping it removes the `<style>` element from the DOM entirely in slide mode, both on nbviewer and in the locally converted slides.

I don't know if the same behavior existed at the time this bug was opened or not, but it does seem to be the case today. I'm going to close this out as resolved. Feel free to comment if you still can't get a custom style to apply in slide mode, even when the style is included as a slide.
