### ISSUE TITLE
Notebook Stuck with [*]

### ISSUE THREAD

**Issue by mmocco** [jupyter/nbviewer#570]
I'm trying to compile a simple file but my computer is being slowed immensely and the notebook cannot continue after the second cell. 

first cell compiles
`import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor`

second cell has the problem 
`"""
Read in train and test as Pandas DataFrames
"""
df_train = pd.read_csv("train.csv")
df_test = pd.read_csv("test.csv")`

files are in the following directory 
![screen shot 2016-02-08 at 8 27 18 pm](https://cloud.githubusercontent.com/assets/7992816/12905113/7fdee220-cea2-11e5-9504-fc7e300ac537.png)

Both train.csv and test.csv are about 1 GB.
I'm not getting any errors, just the * to the left of the cell.

**Comment by bollwyvl** [comment]
Hi! This might be misfiled!

This repo is for the nbviewer.org site, where one can view _static_ notebooks published elsewhere on the web. If you have a problem with nbviewer, post a link to the offending notebook, and we'll try to help!

If you actually think it is a bug, you look like you might be looking for one of these repos (otherwise, try a mailing list!):
- [jupyter notebook](/jupyter/notebook)
 - or the [mailing list](https://groups.google.com/forum/#!forum/jupyter)
- [pandas](/pydata/pandas)
 - or the [mailing list](https://groups.google.com/forum/#!forum/pydata)

Good Luck! :four_leaf_clover:
