### ISSUE TITLE
Make memcached dependency optional

### ISSUE THREAD

**Issue by yuvipanda** [jupyter/nbviewer#574]
Since mostly when running locally you do not need it, and it requires C bindings to install.

**Comment by yuvipanda** [comment]
Hmm, I tried 'requirements-dev' but not sure if that's in addition to requirements.txt or not.

**Comment by yuvipanda** [comment]
I'll check and open a ticket later about requirements.txt / -dev.txt.

newrelic should also be optional.

**Comment by minrk** [comment]
Just a note that it is already optional (the Python code doesn't require it), but it's in requirements.txt which we use for the deployment of the actual service. We should be able to separate the two, though. `requirements-dev` is what's needed to run the tests.

But perhaps we should really make it a hard dependency, since it would be very ill behaved to run without the cache, and nobody should do that if it's at all possible.

**Comment by parente** [comment]
memcached is no longer in the requirements.txt or requirements-dev.txt. It doesn't get puled in with the pip installed package from pypi either. Going to close this out.
