### ISSUE TITLE
Last figure in notebook does not render.

### ISSUE THREAD

**Issue by degravek** [jupyter/nbviewer#699]
I have a notebook consisting of several Plotly figures. For some reason, the last figure will never render. The notebook in question can be found here:

https://nbviewer.jupyter.org/github/degravek/notebooks/blob/master/project_topic_modeling.ipynb?flush_cache=true

The problem is not related to that last figure itself (i.e., bad syntax, etc.), because if I sub in a different figure, it still won't render. Any ideas on how to fix this? Thanks!

**Comment by parente** [comment]
@degravek is the last figure is the one just above the *Closing Remarks* section? If so, it appears to be rendering properly at the moment:

![screen shot 2018-07-08 at 10 00 42 pm](https://user-images.githubusercontent.com/153745/42427070-7ee2ea4c-82fa-11e8-87fa-5ea9f3eb31d1.png)

Maybe you updated the notebook content to workaround the issue or the bug was resolved in nbviewer. Either way, if you can confirm the plot in question is now working, we can close out this issue.

**Comment by parente** [comment]
I'm going to close this as inactive and probably fixed. Feel free to comment if I'm mistaken.
