### ISSUE TITLE
Jupyter notebook stop running cells (Python3)

### ISSUE THREAD

**Issue by bigmouthstrks** [jupyter/nbviewer#713]
As title says: I'm using Jupyter notebook editor for writing and testing Python 3 code, but after a while i can't run cells anymore, and the editor simply jumps to below's cell.
Thank you anyway.

**Comment by bigmouthstrks** [comment]
Hello?

**Comment by damontallen** [comment]
Just a couple points, this is not a nbviewer issue and can't be since nbviewer simple renders publically hosted notebooks for web viewing.  This issue would fall under [notebook](https://github.com/jupyter/notebook).  Second, try posting on [Stack Overflow](https://stackoverflow.com/) or the [IPython reddit](http://www.reddit.com/r/ipython) where you can add samples of your code for review first to see if someone there has experienced your issue and solved it.  To be clear, I am not one of the devs of nbviewer but I have seen your two posts and just realized you haven't received feedback.  Lastly, your question does not contain any information that would help in the diagnosis of the problem.  When you post you need to include your OS, notebook version, Python version, Anaconda version, and code snippet that duplicates the problem.

**Comment by bigmouthstrks** [comment]
@damontallen Thanks for your response, i'm kind of newbie at all this stuff (Stack overflow,github and Python development)
