### ISSUE TITLE
Working with Jupyter in Science not convenient because of issues with converting- Are there solutions?

### ISSUE THREAD

**Issue by HenrikEckermann** [jupyter/nbviewer#719]
Hi all,

I am did some Data Analysis in Python and although uncommon, my Prof wants me to print the Data Analysis out.

Now I ran into trouble because:

1. The images I implemented via Markdown in Jupyter were no more included. There are solutions for that online but they do not work for me because after applying those:
2. The formatting changes so that either there is no more coloring or the spaces are weird and not correct or the numbering (from the list) is not correct anymore.

For me this is a big issue. I do not want to switch to RMarkdown because I work in Python a lot but such simple things are so important to share the work with others. I hope somebody can help me out with these issues so that the notebook gets printed as you see it if you look at the 'Print Preview'.

Best

**Comment by damontallen** [comment]
@HenrikEckermann, I think the solution you are looking for is to Download as -> PDF vai LaTeX from the Notebook.  If this doesn't work first thing, you may be missing some packages and you can see what the problems are by using "jupyter nbconvert your_notebook.ipynb --to pdf " in the terminal and look for any error messages.

I am making the assumption that your advisor wants you to print out your research and then hand it over rather than wanting you to be able to "fix the website" and make printing work there.  FYI I'm not a dev for nbviewer but I saw your issue and thought nbconvert would be a better tool for what you are trying to do.

**Comment by HenrikEckermann** [comment]
@damontallen Thanks for your input.

That was one of the first things I tried. I do not get any errors and I get a pdf as output but the formatting is changed. For example, instead of Header 1 (Markdown) I get '0.1'  and the the next header is '0.2' and so forth. Dataframes that are so nicely shown as tables with frames in Jupyter loose their frames and finally also longer lines of code are not printed but there is a cutoff to the right.

That are the issues I have with this method. I tried many other options and searched online. It seems like many people run into similar issues. I think that this is a very important issue that Jupyter Notebook has. Because otherwise it would be perfect for researchers. It may already be a good tool for students who are familiar with github and html etc. because they can share their work easily online which is the future.

But in this case, my Prof wants it printed and it should be not problem to get a pdf for example. I did not run into this issue with for example RMarkdown. I could make pdf or even word files right away without any bugs. I wish I could do that in Jupyter.

**Comment by rgbkrk** [comment]
If you print with the [nteract desktop app](https://github.com/nteract/nteract), it comes out _really_ close to what you see in the UI:

App:
![screen shot 2017-09-12 at 10 19 26 am](https://user-images.githubusercontent.com/836375/30339464-f250922e-97a3-11e7-9201-cf27c0f63d7d.png)

PDF:
![screen shot 2017-09-12 at 10 19 42 am](https://user-images.githubusercontent.com/836375/30339465-f25710fe-97a3-11e7-8f26-d62bf8fe506e.png)

However, if you do any markdown that we don't support (github flavor for example), it won't look the same as a jupyter notebook.

**Comment by HenrikEckermann** [comment]
@rgbkrk Thanks for that input. I definitively want to give that a try. I installed the mac version of nteract. Then I tried to open the jupyter python notebook (both locally by just double clicking it) and from the nteract via File-->open etc...

It opens the notebook but I get the error 'Error_Kernel_Launch_Failed'. I try to fix that error and then get back here if I could successfully print my notebook.

**Comment by rgbkrk** [comment]
You'll need to register your Anaconda root environment as a kernel at the moment using:

```
python -m ipykernel install --user
```

at the command line

**Comment by HenrikEckermann** [comment]
@rgbkrk 
Thank again. Now I could open the notebook without errors. The outlook nteract is very nice. I exported as pdf and although the outlook here is VERY nice, too, I have 2 problems:

1. The images that I implemented with markdown are not shown. I guess that could be fixed easily if I find out what is going wrong here but...
2. The tables and some text are cut off and not displayed (see examples in attached pictures.

![screenshot_2017-09-12 20 07 39_zor3zk](https://user-images.githubusercontent.com/22709846/30341466-5e7dd0d6-97f6-11e7-9369-7ccc8c4235a8.jpg)
![screenshot_2017-09-12 20 07 58_2yqi43](https://user-images.githubusercontent.com/22709846/30341467-5eac1932-97f6-11e7-8ae7-d6b9640a5f8b.jpg)
![screenshot_2017-09-12 20 08 22_krgjgj](https://user-images.githubusercontent.com/22709846/30341468-5eae8dd4-97f6-11e7-9849-cb7b32916812.jpg)

**Comment by rgbkrk** [comment]
Are you able to share a copy of your notebook for me to check out? Either a link to one on GitHub or even a PR to nteract (for people to reference).

**Comment by HenrikEckermann** [comment]
@rgbkrk 
I sent it to you via the emailadress in your githubprofile.

**Comment by damontallen** [comment]
@HenrikEckermann, The issue with heading comes from a missing top level heading at the beginning, change the first heading to # instead of ##.  As for the table frames, that is by design for easier hard copy reading.  Lastly, the code running off the edge of the page is because those lines are longer than 80 characters (see [Python PEP8 Style Guide](https://www.python.org/dev/peps/pep-0008/#maximum-line-length)).  For the 80 character limit, I use the nbextension [Rulers](http://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/ruler/readme.html) available through the [jyputer_contrib_nbextensions](http://jupyter-contrib-nbextensions.readthedocs.io/en/latest/#) collection.

Personally, I've gotten into the habit of exporting to LaTeX, cleaning everything up, then converting to a pdf.  This does require using a LaTeX editor though and some familiarity with LaTeX so it may not be for you.

**Comment by damontallen** [comment]
@HenrikEckermann, The issue with heading comes from a missing top level heading at the beginning, change the first heading to # instead of ##.  As for the table frames, that is by design for easier hard copy reading.  Lastly, the code running off the edge of the page is because those lines are longer than 80 characters (see [Python PEP8 Style Guide](https://www.python.org/dev/peps/pep-0008/#maximum-line-length)).  For the 80 character limit, I use the nbextension [Rulers](http://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/ruler/readme.html) available through the [jyputer_contrib_nbextensions](http://jupyter-contrib-nbextensions.readthedocs.io/en/latest/#) collection.

Personally, I've gotten into the habit of exporting to LaTeX, cleaning everything up, then converting to a pdf.  This does require using a LaTeX editor though and some familiarity with LaTeX so it may not be for you.

**Comment by HenrikEckermann** [comment]
Thanks for the suggestion @damontallen . I do not yet know LaTex and wont be able to learn it in the short run. But I will check if it works if I change the heading and make shorter lines of code.

**Comment by parente** [comment]
Hi all. This issue has been inactive for quite some time now. It looks like a few different ideas were proposed to improve the printing of notebooks. Is it OK to close and continue discussions about improvements in the nbconvert and/or to nteract projects?

**Comment by rgbkrk** [comment]
That sounds good to me, this can be closed for nbviewer.
