### ISSUE TITLE
Error 503 No healthy backends

### ISSUE THREAD

**Issue by mkempenaar** [jupyter/nbviewer#746]
Hi,

We're experiencing the above error when trying to access any page on nbviewer, even though [the status page](http://status.jupyter.org) lists everything as operational.

Complete error message:

```
No healthy backends

Guru Mediation:

Details: cache-ams4136-AMS 1513241013 4109427764
```

About a year ago we experienced the same issues which seemed to be resolved for quite some time, see closed [issue 607](https://github.com/jupyter/nbviewer/issues/607).

**Comment by takluyver** [comment]
The status page has been updated now, and @minrk is investigating.

**Comment by 2DQRCODE** [comment]
Error 503 No healthy backends
No healthy backends

Guru Mediation:
Details: cache-mia17624-MIA 1529559699 2698939556

**Comment by parente** [comment]
The 503 error typically happens when there is an issue with the operation of the hosted public instance. As nbviewer.jupyter.org seems to be healthy right now, I'm going to close this as resolved. If there's a particular action you're taking that repeatedly leads to 503 errors, please comment to let us know.

**Comment by Lashuk1729** [comment]
I'm facing the following error on nbviewer.

```
Error 503 No healthy backends
No healthy backends

Guru Mediation:
Details: cache-sin18024-SIN 1571207069 2184144586```

**Comment by krinsman** [comment]
@Lashuk1729 see https://github.com/jupyter/nbviewer/issues/857
