### ISSUE TITLE
How to share only pyLDAvis.graphlab to other 

### ISSUE THREAD

**Issue by Rahulvks** [jupyter/nbviewer#762]
HI 

Am working on topic modeling using LDA and Genism. How to share the the `pyLDAvis.graphlab.prepare(topic_model, bows)` to other user. I want to share only the interactive graphical pyLDAvis output.

**Comment by parente** [comment]
Hi @RVKRM. It looks like the interactive output from pyLDAvis does work in nbviewer based on http://nbviewer.jupyter.org/github/bmabey/pyLDAvis/blob/master/notebooks/pyLDAvis_overview.ipynb. Are you looking to hide all of the other notebook content and only have the output showing? If so, there's no support currently in nbviewer to support input and/or output hiding based on nbconvert tags or otherwise. That said, you can inject a snippet of JS code into your notebook to hack a button to show/hide content into your particular notebook on nbviewe. See http://mindtrove.info/code-hiding-on-nbviewer/.

**Comment by RVKRM** [comment]
Thank you @parente.

**Comment by krinsman** [comment]
@Rahulvks It seems like the above answer helped you with your question. Thus I am tentatively closing this issue as resolved. Please let me know whether it should be reopened.
