### ISSUE TITLE
Notebook not loading

### ISSUE THREAD

**Issue by PhatWabbit** [jupyter/nbviewer#764]
Hey there,

This notebook isn't loading. 

https://nbviewer.jupyter.org/github/miguelcleon/ODM2API-ipython-notebooks/blob/master/Using%20ODM2API%20and%20SQLAlchemy%20to%20load%20time%20series%20data%20from%20a%20file.ipynb

All the other notebooks in this guy's repository works, but this notebook is the one I really need access to. Any help is appreciated. 

Thank you,
Dan W

**Comment by dsblank** [comment]
You can always see it in github directly:

https://github.com/miguelcleon/ODM2API-ipython-notebooks/blob/master/Using%20ODM2API%20and%20SQLAlchemy%20to%20load%20time%20series%20data%20from%20a%20file.ipynb

or even see it raw (by clicking raw in github).

This notebook may have been edited by hand to remove the password.

**Comment by PhatWabbit** [comment]
Thanks for the advice!

**Comment by parente** [comment]
The GitHub notebook rendering code must be more forgiving of notebook schema problems. @dsblank is right: the notebook in question fails validation using nbformat: https://nbviewer.jupyter.org/gist/parente/6108826482f4253d92c3cce75754041e.

Since there's a workaround  and technically the notebook in question is broken, I'm going to close this as resolved.
