### ISSUE TITLE
Github render of notebook fails to render certain equations.

### ISSUE THREAD

**Issue by eduardgrebe** [jupyter/nbviewer#877]
**Describe the bug**
Certain equations on their own line in markdown cells and wrapped in `$$` do not render in Github nbviewer rendered view, while displaying correctly in jupyterlab.

**To Reproduce**
1. Go to https://github.com/eduardgrebe/weusten-residual-risk/blob/master/ResidualRisk.ipynb
2. Scroll down to the markdown cell between code cells 3 and 4
4. Notice the second equation in the cell, which displays as:

`$$P_{nondetection}= 1 - P_{+,initial} \cdot (1 - P_{-,retest})$$`

and the last line where two equations display on one line as unrendered text ``$$...$$$$...$$``. The equations are in fact on their own lines and the notebook source has `\n` delimiters as expected.

**Expected behavior**
Rendered equations, as in jupyterlab

**Screenshots**
The first screenshot shows the Github render, and the second shows the Jupyterlab render.

![Screen Shot 2019-12-18 at 17 25 06](https://user-images.githubusercontent.com/613657/71137320-8a88a280-21bc-11ea-8e51-f53e80c142f4.png)

![Screen Shot 2019-12-18 at 17 26 17](https://user-images.githubusercontent.com/613657/71137325-91171a00-21bc-11ea-920d-0aee14654ed8.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.2
 - Browser FireFox
 - Version 71.0

**Additional context**
In use on local machine, where functions as expected:
* jupyterlab 1.2.4
* Python 3.8.0

**Comment by krinsman** [comment]
What happens when you export the page to HTML from JupyterLab?

It is unclear from this whether this is an issue with NBViewer or with NBConvert.

https://github.com/jupyter/nbconvert

Also it might be the case that NBViewer is using an older version of NBConvert that hadn't fixed this issue but JupyterLab is using a more up-to-date version.

**Comment by eduardgrebe** [comment]
My apologies for not seeing the question. The equations are rendered correctly in HTML exports from JupyterLab. I have added the export to my repo, in case you want to compare the github render to the JupyterLab render.

**Comment by krinsman** [comment]
Yes, I'm not sure what the cause of the issue is either, but I do see the same problems you see with some of the `$$`'s. To the best of my knowledge GitHub's notebook rendering doesn't use NBViewer (I think they use some custom, in-house built tool written in Ruby), so I don't think there is anything we're able to do.

And of course GitHub's code is all closed source, so there's nowhere to open issues which isn't very helpful. At least that has been my experience when encountering GitHub bugs.
