### ISSUE TITLE
400 error for viewing getting_started.ipynb

### ISSUE THREAD

**Issue by naliamm** [jupyter/nbviewer#886]
Hi,

I can't open the getting_started.ipynb notebook. It gives me this error - 400: Bad Request // Error reading JSON notebook. However, I can view all the other documentation_builder notebooks fine.

Thanks,

**Comment by krinsman** [comment]
@naliamm  Thanks for contributing to NBViewer!

Can you clarify which notebook you are trying to view on the website? 

I am able to view the Ruby `getting_started.ipynb` on the front page: https://nbviewer.jupyter.org/github/SciRuby/sciruby-notebooks/blob/master/getting_started.ipynb

**Comment by naliamm** [comment]
Hi @krinsman ,

I'm trying to use IPython notebook to view that.

Thanks,

**Comment by krinsman** [comment]
> Hi @krinsman ,
> 
> I'm trying to use IPython notebook to view that.
> 
> Thanks,

@naliamm **1.** To clarify, what is "that"?

I want to help you. Right now I am very confused about what the problem is. This is preventing me from being able to reproduce the problem, and thus preventing me from having any opportunity to figure out a potential solution to the problem.

**2.** What is the URL link, if any, of the notebook in question? What is `getting_started.ipynb`? Is it the Ruby notebook?

**3.** Are you trying to access the URL link from a web browser https://nbviewer.jupyter.org/github/SciRuby/sciruby-notebooks/blob/master/getting_started.ipynb ?

**4.** Or are you running your own NBViewer server on your computer, and that server is not able to access `<base_url>/github/SciRuby/sciruby-notebooks/blob/master/getting_started.ipynb`?

**Comment by naliamm** [comment]
Hi @krinsman ,

Sorry for the confusion. I'm new to this. Actually, I was about to paste the link here but then I just realized I'm on the wrong site. I thought I'm at cobrapy github.

Thanks,

**Comment by krinsman** [comment]
No worries, thank you for reaching out!
