### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by abhishekhalder** [jupyter/nbviewer#917]
Hi!

I am getting 404 error for 
https://github.com/abhishekhalder/AM-231/blob/master/Spring20Homeworks/HW1.ipynb
<img width="766" alt="Screen Shot 2020-04-09 at 11 29 12 PM" src="https://user-images.githubusercontent.com/11708923/78968619-eeabdb00-7ab9-11ea-8fbc-917105e8fbc6.png">

Not sure exactly what the issue is. I have used the exact same formats of the URL before. Issue tested on Chrome, Safari in MacOS Catalina 10.15.3.

**Comment by krinsman** [comment]
Thank you for contributing to NBViewer!

The link is working for me now! https://github.com/abhishekhalder/AM-231/blob/master/Spring20Homeworks/HW1.ipynb

Is it working for you now?

This seems to be similar to previous issues, where the problem seems to have been with the GitHub API, over which we have no control.

https://github.com/jupyter/nbviewer/issues/903
https://github.com/jupyter/nbviewer/issues/916
https://github.com/jupyter/nbviewer/issues/912
https://github.com/jupyter/nbviewer/issues/915

**Comment by abhishekhalder** [comment]
It seems to be working fine now. Thanks.
