### ISSUE TITLE
nbviewer is rendering my ipynb in abnormal way.

### ISSUE THREAD

**Issue by gritmind** [jupyter/nbviewer#920]
Hello,
First, thanks for using Jupyter Notebook Viewer (nbviewer).
I think, I found a bug. Please check the below.

nbviewer is rendering my ipynb(`ch9_note.ipynb`) in abnormal way. 
Without any description, it will be better to click directly the below link.

https://nbviewer.jupyter.org/github/gritmind/my-review-notes/blob/master/code/book/pymldg/note_ipynb/ch9/ch9_note.ipynb

As you see, the rendering is abnormal. It renders something like in a horizental way.

The below link is just from github with the same ipynb file(`ch9_note.ipynb`).

https://github.com/gritmind/my-review-notes/blob/master/code/book/pymldg/note_ipynb/ch9/ch9_note.ipynb

You can see the rendering is good (but, slow because of not using nbviewer :D). 
On this account, the ipynb file(`ch9_note.ipynb`) itself is good.

Therefore, I guess, the error is related to nbviewer itself.
Would you check this bug report? Thanks.

plus...

Interestingly, another file(`ch1_note.ipynb`) is fine. You can see the below link, nbviewer successfully renders it.

https://nbviewer.jupyter.org/github/gritmind/my-review-notes/blob/master/code/book/pymldg/note_ipynb/ch1/ch1_note.ipynb

Is there any difference between `ch1_note.ipynb` and `ch9_note.ipynb` in accordance with nbviewer redering?

**Comment by krinsman** [comment]
@gritmind Thank you for contributing to NBViewer!

What happens when you run the notebook in Jupyter Notebook or JupyterLab, and then do "Save as -> HTML" or (ctrl-p/cmd-p) -> "Save as PDF"?

This seems like it might be an issue with one of NBViewer's upstream dependencies, [nbformat](https://github.com/jupyter/nbformat).

**Comment by gritmind** [comment]
@krinsman Thanks for your feedback.

There are the same phenomenons when I save the `.ipynb` as `.html` and see that `html`.

That is, `ch2_note.html` and `ch9_note.html` are rendered in abnormal way. Instead, `ch1_note.html` is successfully rendered.

Are there ways to handle with this problem for myself? Is it related to the version of Jupyter notebook?

**Comment by krinsman** [comment]
I don't know if it is something you can handle by yourself. It could perhaps be an issue with the version of Jupyter notebook, inasmuch as the default version of `nbformat` probably varies between versions of Jupyter notebook. 

One thing you could check is the metadata of the notebook (I think there is a metadata explorer you can use to do this with jupyterlab or a JupyterLab extension, otherwise you would need to open the notebook as a text file (or look at the file as 'raw' on GitHub). The `nbformat` entry of the JSON is near the very end of the files.

In other words, it sounds like an issue with `nbformat`, which you might want to open an issue with  here:

https://github.com/jupyter/nbformat/issues

For now I am tentatively closing this issue as most likely not relating to NBViewer -- please update with new information isolating this as an issue with NBViewer if it occurs.

Looking at the notebooks you mentioned, it seems like they all use the same version of NBFormat (again near the end as a text file). So honestly I'm not really sure.

![Снимок экрана 2020-04-23 в 18 03 11](https://user-images.githubusercontent.com/31422259/80164122-0476d100-858d-11ea-80af-dc7376565201.png)
![Снимок экрана 2020-04-23 в 18 03 49](https://user-images.githubusercontent.com/31422259/80164127-080a5800-858d-11ea-9c41-f6571f840929.png)

**Comment by gritmind** [comment]
@krinsman Thank you for your feedback. I got it. :D
