### ISSUE TITLE
Iframes seem to break the nbviewer

### ISSUE THREAD

**Issue by pfctdayelise** [jupyter/nbviewer#94]
By "break" I mean, it stops rendering any more cells after the first iframe. Works fine in a local notebook. ipython 0.13.2.

Example: 
https://gist.github.com/pfctdayelise/5926494
http://nbviewer.ipython.org/5926494

**Comment by bollwyvl** [comment]
This appears to be fixed now. Please reopen if there is some other concern.

**Comment by tdpetrou** [comment]
First github post so please feel free to bash me senselessly. 

IFrame function is broken for me
[notebook](https://github.com/tdpetrou/Data-Science-in-Two-Minutes/blob/master/test.ipynb)
[viewer](https://nbviewer.jupyter.org/github/tdpetrou/Data-Science-in-Two-Minutes/blob/master/test.ipynb)

Also, is there a way to prevent scrolling like in a normal html iframe?

**Comment by Carreau** [comment]
The rendering on GitHub is sanitized for security reason, so iframe is are stripped. 

For nbviewer this is simply because what you try to embed is over https, and nbviewer is over https. 
The browsers restrictions prevent to load insecure content over a secured connexion, you can see that by opening the developer console: `view` > `developer` > `javascript console` (likely):

![screen shot 2016-06-17 at 16 24 22](https://cloud.githubusercontent.com/assets/335567/16167288/0b2f3256-34a8-11e6-9951-4a5b8b4c68e4.png)

**Comment by Carreau** [comment]
Opps posted too fast, fixed typo above and : change your code to use `https://ipython.org` shoud likely work. There  might be extra options for iframes, but I don't think we can prevent scrolling.

**Comment by tdpetrou** [comment]
Thanks for replying so fast to such a low level peon such as myself about a minor issue.

nbviewer is still busted after change to https. console error is 'Failed to load resource: net::ERR_CONNECTION_TIMED_OUT'

Also, scroll lock is possible simply using the HTML function and attribute 'scrolling' in the iframe

**Comment by Carreau** [comment]
> Thanks for replying so fast to such a low level peon such as myself about a minor issue.

We all started by posting a first issue on github at some point. we have no reason to take more time to respond to some people than other.

> net::ERR_CONNECTION_TIMED_OUT'

Drop the `www.`, iframe dont support redirect well.

**Comment by tdpetrou** [comment]
Thanks. All working.

**Comment by Carreau** [comment]
> Thanks. All working.

Great, welcome to the party !
